# Generated by Django 4.2 on 2023-07-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='separately_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotels',
            name='separately_booked',
            field=models.BooleanField(default=False),
        ),
    ]
