# Generated by Django 4.2 on 2023-07-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_flights_separately_booked_hotels_separately_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookflight',
            name='flight',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookpackage',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
    ]
