# Generated by Django 4.2 on 2023-08-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_date']},
        ),
    ]
