# Generated by Django 4.2 on 2023-08-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='description',
            field=models.TextField(default='Fill in this field'),
        ),
    ]
