# Generated by Django 4.2 on 2023-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0008_hotels_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpackage',
            name='city',
            field=models.CharField(default='No', max_length=100),
        ),
    ]
